package main

import (
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCountOracleIgnoresSubtests(t *testing.T) {
	// Go indents subtest result lines; only top-level TestCFFDRS* functions are
	// the fifteen-or-so the docs and the gate talk about.
	out := `=== RUN   TestCFFDRSBuildupEffect
--- SKIP: TestCFFDRSBuildupEffect (0.00s)
=== RUN   TestCFFDRSSurfaceROS
=== RUN   TestCFFDRSSurfaceROS/C1
    --- SKIP: TestCFFDRSSurfaceROS/C1 (0.00s)
--- PASS: TestCFFDRSSurfaceROS (0.31s)
=== RUN   TestSomethingElse
--- PASS: TestSomethingElse (0.00s)
PASS
`
	total, skipped := countOracle(out)
	if total != 2 {
		t.Errorf("total = %d, want 2 (subtests and non-oracle tests must not count)", total)
	}
	if skipped != 1 {
		t.Errorf("skipped = %d, want 1 (the indented subtest skip must not count)", skipped)
	}
}

func TestParseMetaReadsTheVersionsRecordedIntoTheFixture(t *testing.T) {
	head := `{
 "note": "generated by testdata/gen_cffdrs_reference.R; do not edit by hand",
 "oracle": "cffdrs R package (Canadian Forest Service)",
 "cffdrs_version": "1.9.2",
 "r_version": "R version 4.6.1 (2026-02-28)",
 "cases": [`
	m := parseMeta(head)
	if m.cffdrs != "1.9.2" || m.r != "R version 4.6.1 (2026-02-28)" {
		t.Errorf("got %+v", m)
	}
	if got := shortR(m.r); got != "4.6.1" {
		t.Errorf("shortR = %q, want 4.6.1", got)
	}
	if got := shortR(""); got != "unknown" {
		t.Errorf("shortR(\"\") = %q", got)
	}
}

// The metadata is read from the head of the file while the digest is taken over
// the whole of it. A bug there would hash only the first 4 KB and call any
// fixture with the right header a match.
func TestDigestCoversTheWholeFileNotJustTheHead(t *testing.T) {
	dir := t.TempDir()
	head := `{"cffdrs_version": "1.9.2", "r_version": "R version 4.6.1", "cases": [`

	write := func(name, body string) string {
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
		return p
	}
	// Two files with identical headers, differing only well past 4 KB.
	padding := strings.Repeat(`{"fuel": "C1", "ros": 5.0},`, 500)
	a := write("a.json", head+padding+`{"fuel": "C2", "ros": 9.0}]}`)
	b := write("b.json", head+padding+`{"fuel": "C2", "ros": 9.5}]}`)

	sumA, metaA, err := digestAndMeta(a)
	if err != nil {
		t.Fatal(err)
	}
	sumB, _, err := digestAndMeta(b)
	if err != nil {
		t.Fatal(err)
	}
	if sumA == sumB {
		t.Error("two fixtures differing past the header hashed identically")
	}
	if metaA.cffdrs != "1.9.2" {
		t.Errorf("metadata not read from a streamed file: %+v", metaA)
	}

	// And the digest must be the real one, not one over a truncated read.
	raw, err := os.ReadFile(a)
	if err != nil {
		t.Fatal(err)
	}
	want := sha256.Sum256(raw)
	if sumA != hex.EncodeToString(want[:]) {
		t.Errorf("digest %s is not sha256 of the file", sumA)
	}
}

// The four states the gate exists to tell apart. Auditing survives all of them;
// porting does not.
func TestVerdictSeparatesAuditFromPort(t *testing.T) {
	for _, tc := range []struct {
		name        string
		setup       func(*verdict)
		mode        string
		wantExit    int
		wantCanPort bool
	}{
		{
			name:  "everything present",
			setup: func(v *verdict) {},
			mode:  "port", wantExit: exitReady, wantCanPort: true,
		},
		{
			name:  "no fixture blocks porting but not auditing",
			setup: func(v *verdict) { v.block("no fixture") },
			mode:  "port", wantExit: exitDegraded, wantCanPort: false,
		},
		{
			name:  "the same session may still audit",
			setup: func(v *verdict) { v.block("no fixture") },
			mode:  "audit", wantExit: exitReady, wantCanPort: false,
		},
		{
			name: "red tests stop everything",
			setup: func(v *verdict) {
				v.CanAudit = false
				v.block("go test ./... is red")
			},
			mode: "audit", wantExit: exitRed, wantCanPort: false,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			v := &verdict{Mode: tc.mode, CanAudit: true, CanPort: true}
			tc.setup(v)
			decide(v)
			if v.Exit != tc.wantExit {
				t.Errorf("exit = %d, want %d", v.Exit, tc.wantExit)
			}
			if v.CanPort != tc.wantCanPort {
				t.Errorf("CanPort = %v, want %v", v.CanPort, tc.wantCanPort)
			}
		})
	}
}

// A degraded session must be told plainly what it may not do — the report is the
// only thing standing between it and a hand-transcribed coefficient nobody checked.
func TestDegradedReportSaysWhatIsForbidden(t *testing.T) {
	v := &verdict{Mode: "port", CanAudit: true, CanPort: true, TestsRun: true, TestsPass: true}
	v.block("there is no testdata/cffdrs.json, so every TestCFFDRS* skips.")
	decide(v)

	var sb strings.Builder
	printVerdict(&sb, v)
	out := sb.String()
	for _, want := range []string{"AUDIT ONLY", "do NOT port", "cffdrs.json"} {
		if !strings.Contains(out, want) {
			t.Errorf("the verdict does not say %q:\n%s", want, out)
		}
	}
}

func TestReadyReportDoesNotHedge(t *testing.T) {
	v := &verdict{Mode: "port", CanAudit: true, CanPort: true, TestsRun: true, TestsPass: true,
		FixturePresent: true, FixtureBytes: 9500000, FixtureCFFDRS: "1.9.2",
		FixtureR: "R version 4.6.1", OracleTests: 12}
	decide(v)

	var sb strings.Builder
	printVerdict(&sb, v)
	out := sb.String()
	if !strings.Contains(out, "READY") {
		t.Errorf("got:\n%s", out)
	}
	if strings.Contains(out, "AUDIT ONLY") {
		t.Errorf("a ready session was told it may not port:\n%s", out)
	}
}

// The digest is taken over the whole file and the file carries r_version — build
// date included — inside it. So a mismatch cannot, on its own, mean the numbers
// moved, and the report must not say it does. Observed for real: a fixture built
// at the pinned cffdrs 1.9.2 / R 4.6.1 hashed differently and still passed all
// twelve oracle tests.
func TestDigestMismatchDoesNotClaimTheNumbersMoved(t *testing.T) {
	v := &verdict{Mode: "port", CanAudit: true, CanPort: true,
		TestsRun: true, TestsPass: true, OracleTests: 12, OracleSkipped: 0,
		FixturePresent: true, FixtureCFFDRS: "1.9.2", FixtureR: "R version 4.6.1 (2026-06-24)",
		PinCFFDRS: "1.9.2", PinR: "4.6.1",
		FixtureSHA: "aaaa", RecordedSHA: "bbbb"}
	v.block("the fixture reports the pinned versions (cffdrs 1.9.2, R 4.6.1) but its digest " +
		"is not the recorded one. That is one of two things and the digest cannot separate " +
		"them: a different BUILD of the same R version, or reference numbers that actually moved.")
	decide(v)

	var sb strings.Builder
	printVerdict(&sb, v)
	out := sb.String()
	if !strings.Contains(out, "cannot separate them") {
		t.Errorf("the report does not admit the ambiguity:\n%s", out)
	}
	// It must still block: evidence the values agree with this package is not
	// evidence they match the fixture the ledger's claims were measured against.
	if v.CanPort || v.Exit != exitDegraded {
		t.Errorf("a mismatched digest did not block porting (exit %d)", v.Exit)
	}
}

// io.Copy hands over arbitrary chunks, and a pattern straddling two of them is
// the failure this class exists to avoid. Feed it every possible split.
func TestSubstringCounterSurvivesEveryChunkBoundary(t *testing.T) {
	body := `{"fuel": "C1"},{"fuel": "C2"},{"fuel": "C3"}`
	const want = 3

	for split := 1; split < len(body); split++ {
		c := &substringCounter{pattern: []byte(`"fuel"`)}
		if _, err := c.Write([]byte(body[:split])); err != nil {
			t.Fatal(err)
		}
		if _, err := c.Write([]byte(body[split:])); err != nil {
			t.Fatal(err)
		}
		if c.count != want {
			t.Fatalf("split at %d: counted %d, want %d", split, c.count, want)
		}
	}

	// And one byte at a time, which is every boundary at once.
	c := &substringCounter{pattern: []byte(`"fuel"`)}
	for i := 0; i < len(body); i++ {
		c.Write([]byte{body[i]})
	}
	if c.count != want {
		t.Errorf("byte at a time: counted %d, want %d", c.count, want)
	}
}

func TestHeadWriterKeepsOnlyTheHead(t *testing.T) {
	w := &headWriter{limit: 8}
	w.Write([]byte("12345"))
	w.Write([]byte("67890"))
	w.Write([]byte("abcdef"))
	if got := w.String(); got != "12345678" {
		t.Errorf("got %q, want 12345678", got)
	}
}

// The count is taken in the same streaming pass as the digest, so a real file
// exercises both against each other.
func TestCaseCountIsTakenOverTheWholeStreamedFile(t *testing.T) {
	dir := t.TempDir()
	var b strings.Builder
	b.WriteString(`{"cffdrs_version": "1.9.2", "r_version": "R version 4.6.1", "cases": [`)
	const n = 5000
	for i := 0; i < n; i++ {
		b.WriteString(`{"fuel": "C1", "ffmc": 90, "ros": 5.0},`)
	}
	b.WriteString(`{"fuel": "C2"}]}`)

	path := filepath.Join(dir, "f.json")
	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		t.Fatal(err)
	}
	_, meta, err := digestAndMeta(path)
	if err != nil {
		t.Fatal(err)
	}
	if meta.cases != n+1 {
		t.Errorf("counted %d cases, want %d", meta.cases, n+1)
	}
	if meta.cffdrs != "1.9.2" {
		t.Errorf("metadata lost: %+v", meta)
	}
}

// A stale count is prose drift, not a reason to refuse a port: once the digest
// matches, the same bytes cannot have a different number of cases, so a mismatch
// can only mean the docs are behind.
func TestStaleCaseCountIsANoteNotABlocker(t *testing.T) {
	v := &verdict{Mode: "port", CanAudit: true, CanPort: true,
		FixtureCases: 23532, DocumentedCases: 18400}
	checkCaseCount(v)
	decide(v)

	if !v.CanPort || v.Exit != exitReady {
		t.Errorf("a stale case count blocked porting (exit %d, blockers %v)", v.Exit, v.Blockers)
	}
	if len(v.Notes) != 1 || !strings.Contains(v.Notes[0], "18400") {
		t.Errorf("notes = %v, want one naming the number to grep for", v.Notes)
	}

	var sb strings.Builder
	printVerdict(&sb, v)
	if !strings.Contains(sb.String(), "does not block") {
		t.Errorf("the report does not distinguish a note from a blocker:\n%s", sb.String())
	}
}

func TestMatchingCaseCountSaysNothing(t *testing.T) {
	v := &verdict{Mode: "port", CanAudit: true, CanPort: true,
		FixtureCases: 23532, DocumentedCases: 23532}
	checkCaseCount(v)
	if len(v.Notes) != 0 {
		t.Errorf("notes = %v, want none", v.Notes)
	}
}
