package fwi

import (
	"encoding/json"
	"errors"
	"io/fs"
	"math"
	"os"
	"sort"
	"sync"
	"testing"
)

// The cffdrs fixture is the only thing that can say the FWI System's
// coefficients here are right rather than self-consistent, exactly as it is for
// package fbp. Its FWI half lives under "fwi_cases" in the same file as fbp's
// "cases", generated by the same script at the same pins:
//
//	testdata/regen-cffdrs.sh
//
// Each row has a kind naming what produced it (see gen_cffdrs_reference.R):
// the six component functions called directly, fwi() for one day, fwi() over a
// multi-day chain, and fwi() over cffdrs' own test_fwi sample. Input columns
// are named apart from outputs — the ISI grid's FFMC is ffmc_in — so a row can
// be read without knowing which block wrote it.
type fwiCase struct {
	Kind  string `json:"kind"`
	Chain string `json:"chain"`
	Day   int    `json:"day"`
	// LatAdjust is nil on kinds that take no latitude. False means the row was
	// generated with lat.adjust = FALSE; see latFor.
	LatAdjust *bool   `json:"lat_adjust"`
	Mon       int     `json:"mon"`
	Lat       float64 `json:"lat"`

	Temp float64 `json:"temp"`
	RH   float64 `json:"rh"`
	WS   float64 `json:"ws"`
	Prec float64 `json:"prec"`

	// Yesterday's codes. On chain and test_fwi rows they are present on day 1
	// only: that is the chain's start, and every later yesterday is the Go
	// side's own previous output.
	FFMCYda *float64 `json:"ffmc_yda"`
	DMCYda  *float64 `json:"dmc_yda"`
	DCYda   *float64 `json:"dc_yda"`

	FFMCIn float64 `json:"ffmc_in"`
	DMCIn  float64 `json:"dmc_in"`
	DCIn   float64 `json:"dc_in"`
	ISIIn  float64 `json:"isi_in"`
	BUIIn  float64 `json:"bui_in"`

	// Outputs. Pointers, because a kind emits only the outputs it is about, and
	// a missing output must not read as a zero that happens to agree.
	FFMC *float64 `json:"ffmc"`
	DMC  *float64 `json:"dmc"`
	DC   *float64 `json:"dc"`
	ISI  *float64 `json:"isi"`
	BUI  *float64 `json:"bui"`
	FWI  *float64 `json:"fwi"`
	DSR  *float64 `json:"dsr"`
}

type fwiFixture struct {
	Oracle        string    `json:"oracle"`
	CFFDRSVersion string    `json:"cffdrs_version"`
	RVersion      string    `json:"r_version"`
	FWICases      []fwiCase `json:"fwi_cases"`
}

const fixturePath = "../testdata/cffdrs.json"

var (
	fixtureOnce sync.Once
	fixture     fwiFixture
	fixtureErr  error
	fixtureGone bool
)

// loadFWI reads the fixture once per test binary: it is 15 MB, and nine tests
// read the same half of it.
func loadFWI(t *testing.T) []fwiCase {
	t.Helper()
	fixtureOnce.Do(func() {
		raw, err := os.ReadFile(fixturePath)
		if errors.Is(err, fs.ErrNotExist) {
			fixtureGone = true
			return
		}
		if err != nil {
			fixtureErr = err
			return
		}
		fixtureErr = json.Unmarshal(raw, &fixture)
	})
	if fixtureGone {
		t.Skip("testdata/cffdrs.json is absent; it is generated, not committed — " +
			"run testdata/regen-cffdrs.sh (needs Docker). See testdata/README.md.")
	}
	if fixtureErr != nil {
		t.Fatalf("read fixture: %v", fixtureErr)
	}
	// A fixture from before the FWI block is a stale fixture, not an absent
	// one. Skipping would let a regeneration that silently dropped the block
	// pass; failing says which digest to expect instead.
	if len(fixture.FWICases) == 0 {
		t.Fatal("the fixture has no fwi_cases: it predates the FWI System block " +
			"(testdata/README.md lists it among the earlier digests). Regenerate it.")
	}
	t.Logf("oracle: %s %s (%s), %d FWI cases",
		fixture.Oracle, fixture.CFFDRSVersion, fixture.RVersion, len(fixture.FWICases))
	return fixture.FWICases
}

func ofKind(cases []fwiCase, kind string) []fwiCase {
	var out []fwiCase
	for _, c := range cases {
		if c.Kind == kind {
			out = append(out, c)
		}
	}
	return out
}

// The same tolerance every TestCFFDRS* in package fbp uses: relative, with an
// absolute floor of 1e-9 below magnitude 1. What it has to absorb is libm, not
// arithmetic — the Go here evaluates cffdrs' expressions in cffdrs' order, and
// the residue is Go's math.Pow/Exp/Log against glibc's, a few ulps. Nothing in
// this file needs a looser one, including the 120-day chains: every code is
// contractive in yesterday's value, so an ulp carried forward shrinks rather
// than grows.
const tol = 1e-9

func closeEnough(got, want float64) bool {
	return math.Abs(got-want) <= tol*math.Max(1, math.Abs(want))
}

// worst tracks the largest relative error seen and how many cases failed, so
// every test can log what it actually asserted rather than only whether it did.
type worst struct {
	t       *testing.T
	name    string
	n, bad  int
	maxRel  float64
	shown   int
	counted map[string]int
}

func newWorst(t *testing.T, name string) *worst {
	return &worst{t: t, name: name, counted: map[string]int{}}
}

func (w *worst) check(got float64, want *float64, format string, args ...any) {
	w.t.Helper()
	if want == nil {
		w.t.Fatalf("%s: a row of this kind has no %s output — the generator and this test disagree about the fixture's shape", w.name, w.name)
	}
	w.n++
	rel := math.Abs(got-*want) / math.Max(1, math.Abs(*want))
	if rel > w.maxRel || math.IsNaN(rel) {
		w.maxRel = rel
	}
	if !closeEnough(got, *want) {
		w.bad++
		if w.shown < 10 {
			w.shown++
			w.t.Errorf("%s = %.17g, cffdrs = %.17g  "+format, append([]any{w.name, got, *want}, args...)...)
		}
	}
}

func (w *worst) branch(name string) { w.counted[name]++ }

// done logs the tally and fails if any named branch the test expects was never
// reached. A pass over a sweep that no longer reaches a branch is a pass for the
// wrong reason — it is the anti-no-op floor every TestCFFDRS* in fbp carries.
func (w *worst) done(minCases int, branches ...string) {
	w.t.Helper()
	if w.bad > w.shown {
		w.t.Errorf("... and %d more %s mismatches", w.bad-w.shown, w.name)
	}
	if w.n < minCases {
		w.t.Errorf("%s: asserted %d cases, want at least %d — the sweep shrank", w.name, w.n, minCases)
	}
	for _, b := range branches {
		if w.counted[b] == 0 {
			w.t.Errorf("%s: branch %q was never reached by the fixture", w.name, b)
		}
	}
	names := make([]string, 0, len(w.counted))
	for k := range w.counted {
		names = append(names, k)
	}
	sort.Strings(names)
	w.t.Logf("%s: %d cases, worst relative error %.3g", w.name, w.n, w.maxRel)
	for _, k := range names {
		w.t.Logf("  %-28s %d", k, w.counted[k])
	}
}

// latFor is the latitude to hand this package for a row. A row generated with
// lat.adjust = FALSE used the unadjusted tables at whatever latitude it names,
// and the unadjusted tables are the ones the northernmost band uses — so those
// rows are asserted at 46 °N, the latitude Van Wagner's DMC table was built
// for. That is the whole of this package's answer to lat.adjust, and these
// rows are what make it an assertion rather than a claim.
func latFor(c fwiCase) float64 {
	if c.LatAdjust != nil && !*c.LatAdjust {
		return 46
	}
	return c.Lat
}

// TestCFFDRSFineFuelMoistureCode asserts FFMC against cffdrs'
// fine_fuel_moisture_code, called directly so RH 100 reaches it unclamped.
//
// ledger: fine_fuel_moisture_code.r
func TestCFFDRSFineFuelMoistureCode(t *testing.T) {
	w := newWorst(t, "FFMC")
	for _, c := range ofKind(loadFWI(t), "ffmc") {
		got := FFMC(*c.FFMCYda, c.Temp, c.RH, c.WS, c.Prec)
		w.check(got, c.FFMC, "(yesterday %v, T %v, RH %v, wind %v, rain %v)",
			*c.FFMCYda, c.Temp, c.RH, c.WS, c.Prec)

		// Branch tally, recomputed from the inputs so it says which path each
		// row took in the oracle's own terms.
		wmo := ffmcCoefficient * (101 - *c.FFMCYda) / (59.5 + *c.FFMCYda)
		switch {
		case c.Prec == ffmcRainThreshold:
			w.branch("rain exactly 0.5 (dry)")
		case c.Prec > ffmcRainThreshold && wmo > 150:
			w.branch("rain, eq. 3b (wmo > 150)")
		case c.Prec > ffmcRainThreshold:
			w.branch("rain, eq. 3a")
		}
		if c.Prec > ffmcRainThreshold {
			ra := c.Prec - ffmcRainThreshold
			var after float64
			if wmo > 150 {
				after = wmo + 0.0015*(wmo-150)*(wmo-150)*math.Sqrt(ra) +
					42.5*ra*math.Exp(-100/(251-wmo))*(1-math.Exp(-6.93/ra))
			} else {
				after = wmo + 42.5*ra*math.Exp(-100/(251-wmo))*(1-math.Exp(-6.93/ra))
			}
			if after > 250 {
				w.branch("moisture cap at 250")
			}
			wmo = math.Min(after, 250)
		}
		rh, temp := c.RH, c.Temp
		ed := 0.942*math.Pow(rh, 0.679) + 11*math.Exp((rh-100)/10) + 0.18*(21.1-temp)*(1-1/math.Exp(rh*0.115))
		ew := 0.618*math.Pow(rh, 0.753) + 10*math.Exp((rh-100)/10) + 0.18*(21.1-temp)*(1-1/math.Exp(rh*0.115))
		switch {
		case wmo > ed:
			w.branch("drying")
		case wmo < ew:
			w.branch("wetting")
		default:
			w.branch("between equilibria")
		}
		// Materially clamped, as opposed to an unchanged 101 coming back an
		// ulp high (see FFMC's doc comment).
		if raw := ffmcUnclamped(*c.FFMCYda, c.Temp, c.RH, c.WS, c.Prec); raw > 101+1e-12 && *c.FFMC == 101 {
			w.branch("clamped at 101")
		}
		if c.RH == 100 {
			w.branch("RH exactly 100")
		}
		if c.RH == 0 {
			w.branch("RH 0")
		}
		if c.WS == 0 {
			w.branch("zero wind")
		}
	}
	// The 0 clamp is absent from this list on purpose: FFMC's doc comment says
	// why it is unreachable, and TestFFMCIsBoundedWithoutItsClamps checks the
	// claim over a far wider grid than any fixture carries.
	w.done(7000, "rain exactly 0.5 (dry)", "rain, eq. 3a", "rain, eq. 3b (wmo > 150)",
		"moisture cap at 250", "drying", "wetting", "between equilibria",
		"clamped at 101", "RH exactly 100", "RH 0", "zero wind")
}

// TestCFFDRSDuffMoistureCode asserts DMC against cffdrs' duff_moisture_code,
// including every lat.adjust band and lat.adjust = FALSE (see latFor).
//
// ledger: duff_moisture_code.r
func TestCFFDRSDuffMoistureCode(t *testing.T) {
	w := newWorst(t, "DMC")
	months := map[int]bool{}
	for _, c := range ofKind(loadFWI(t), "dmc") {
		lat := latFor(c)
		got := DMC(*c.DMCYda, c.Temp, c.RH, c.Prec, c.Mon, lat)
		w.check(got, c.DMC, "(yesterday %v, T %v, RH %v, rain %v, month %d, lat %v, adjust %v)",
			*c.DMCYda, c.Temp, c.RH, c.Prec, c.Mon, c.Lat, *c.LatAdjust)
		months[c.Mon] = true

		if !*c.LatAdjust {
			w.branch("lat.adjust = FALSE")
		} else {
			w.branch(dmcBand(c.Lat))
		}
		switch {
		case c.Prec == dmcRainThreshold:
			w.branch("rain exactly 1.5 (dry)")
		case c.Prec > dmcRainThreshold && *c.DMCYda <= 33:
			w.branch("rain, eq. 13a (<= 33)")
		case c.Prec > dmcRainThreshold && *c.DMCYda <= 65:
			w.branch("rain, eq. 13b (<= 65)")
		case c.Prec > dmcRainThreshold:
			w.branch("rain, eq. 13c (> 65)")
		}
		// At RH 100 the drying term is exactly zero, so what is left is the rain
		// arm alone: a zero there is the pr < 0 floor having fired. If DMC were
		// wrong this tally would be too, but then the check above has already
		// failed.
		if c.Prec > dmcRainThreshold && DMC(*c.DMCYda, c.Temp, 100, c.Prec, c.Mon, lat) == 0 {
			w.branch("rain floored at 0 (pr < 0)")
		}
		if c.Temp < -1.1 {
			w.branch("temp below the -1.1 floor")
		}
		if c.RH > 100 && *c.DMC == 0 {
			w.branch("result floored at 0 (RH > 100)")
		}
		if c.RH == 100 {
			w.branch("RH exactly 100")
		}
	}
	if len(months) != 12 {
		t.Errorf("DMC rows cover %d months, want all 12", len(months))
	}
	w.done(1300,
		"lat > 30", "10 < lat <= 30", "-10 < lat <= 10", "-30 < lat <= -10",
		"-90 <= lat <= -30", "lat < -90 (falls through)", "lat.adjust = FALSE",
		"rain exactly 1.5 (dry)", "rain, eq. 13a (<= 33)", "rain, eq. 13b (<= 65)",
		"rain, eq. 13c (> 65)", "rain floored at 0 (pr < 0)", "temp below the -1.1 floor",
		"result floored at 0 (RH > 100)", "RH exactly 100")
}

func dmcBand(lat float64) string {
	switch {
	case lat <= 30 && lat > 10:
		return "10 < lat <= 30"
	case lat <= -10 && lat > -30:
		return "-30 < lat <= -10"
	case lat <= -30 && lat >= -90:
		return "-90 <= lat <= -30"
	case lat <= 10 && lat > -10:
		return "-10 < lat <= 10"
	case lat < -90:
		return "lat < -90 (falls through)"
	default:
		return "lat > 30"
	}
}

// TestCFFDRSDroughtCode asserts DC against cffdrs' drought_code, including
// every lat.adjust band and lat.adjust = FALSE (see latFor).
//
// ledger: drought_code.r
func TestCFFDRSDroughtCode(t *testing.T) {
	w := newWorst(t, "DC")
	months := map[int]bool{}
	for _, c := range ofKind(loadFWI(t), "dc") {
		lat := latFor(c)
		got := DC(*c.DCYda, c.Temp, c.RH, c.Prec, c.Mon, lat)
		w.check(got, c.DC, "(yesterday %v, T %v, rain %v, month %d, lat %v, adjust %v)",
			*c.DCYda, c.Temp, c.Prec, c.Mon, c.Lat, *c.LatAdjust)
		months[c.Mon] = true

		switch {
		case !*c.LatAdjust:
			w.branch("lat.adjust = FALSE")
		case c.Lat <= -20:
			w.branch("lat <= -20")
		case c.Lat <= 20:
			w.branch("-20 < lat <= 20")
		default:
			w.branch("lat > 20")
		}
		switch {
		case c.Prec == dcRainThreshold:
			w.branch("rain exactly 2.8 (dry)")
		case c.Prec > dcRainThreshold:
			w.branch("rain applied")
			rw := 0.83*c.Prec - 1.27
			if *c.DCYda-400*math.Log(1+3.937*rw/(800*math.Exp(-1**c.DCYda/400))) < 0 {
				w.branch("rain floored at 0 (dr0 < 0)")
			}
		}
		if c.Temp < -2.8 {
			w.branch("temp below the -2.8 floor")
		}
		temp := math.Max(c.Temp, -2.8)
		if 0.36*(temp+2.8)+DCDayLength(c.Mon, lat) < 0 {
			w.branch("evapotranspiration floored at 0")
		}
	}
	if len(months) != 12 {
		t.Errorf("DC rows cover %d months, want all 12", len(months))
	}
	w.done(1200, "lat > 20", "-20 < lat <= 20", "lat <= -20", "lat.adjust = FALSE",
		"rain exactly 2.8 (dry)", "rain applied", "rain floored at 0 (dr0 < 0)",
		"temp below the -2.8 floor", "evapotranspiration floored at 0")
}

// TestCFFDRSFWIInitialSpreadIndex asserts ISI against cffdrs'
// initial_spread_index with fbpMod = FALSE — the FWI System's ISI, which is
// not package fbp's. The wind grid runs to 150 km/h, well past the 40 km/h
// where fbp's high-wind function takes over; a port that borrowed it would
// fail every row above 40.
//
// ledger: initial_spread_index.r (fbpMod = FALSE)
func TestCFFDRSFWIInitialSpreadIndex(t *testing.T) {
	w := newWorst(t, "ISI")
	for _, c := range ofKind(loadFWI(t), "isi") {
		w.check(ISI(c.FFMCIn, c.WS), c.ISI, "(FFMC %v, wind %v)", c.FFMCIn, c.WS)
		switch {
		case c.WS >= 40:
			w.branch("wind >= 40 (no high-wind form)")
		case c.WS == 0:
			w.branch("zero wind")
		}
		if c.FFMCIn == 0 {
			w.branch("FFMC 0")
		}
		if c.FFMCIn == 101 {
			w.branch("FFMC 101")
		}
	}
	w.done(170, "wind >= 40 (no high-wind form)", "zero wind", "FFMC 0", "FFMC 101")
}

// TestCFFDRSBuildupIndex asserts BUI against cffdrs' buildup_index.
//
// ledger: buildup_index.r
func TestCFFDRSBuildupIndex(t *testing.T) {
	w := newWorst(t, "BUI")
	for _, c := range ofKind(loadFWI(t), "bui") {
		w.check(BUI(c.DMCIn, c.DCIn), c.BUI, "(DMC %v, DC %v)", c.DMCIn, c.DCIn)
		switch {
		case c.DMCIn == 0 && c.DCIn == 0:
			w.branch("DMC = DC = 0")
		case c.DMCIn == 0:
			w.branch("DMC = 0, DC > 0")
		case c.DMCIn <= 0.4*c.DCIn:
			w.branch("eq. 27a (DMC <= 0.4 DC)")
		default:
			w.branch("eq. 27b (DMC > 0.4 DC)")
			if *c.BUI == 0 {
				w.branch("eq. 27b floored at 0")
			}
		}
	}
	w.done(95, "DMC = DC = 0", "DMC = 0, DC > 0", "eq. 27a (DMC <= 0.4 DC)",
		"eq. 27b (DMC > 0.4 DC)", "eq. 27b floored at 0")
}

// TestCFFDRSFireWeatherIndex asserts FWI against cffdrs' fire_weather_index.
//
// ledger: fire_weather_index.r
func TestCFFDRSFireWeatherIndex(t *testing.T) {
	w := newWorst(t, "FWI")
	for _, c := range ofKind(loadFWI(t), "fwi") {
		w.check(FWI(c.ISIIn, c.BUIIn), c.FWI, "(ISI %v, BUI %v)", c.ISIIn, c.BUIIn)
		if c.BUIIn > 80 {
			w.branch("eq. 28b (BUI > 80)")
		} else {
			w.branch("eq. 28a (BUI <= 80)")
		}
		if *c.FWI <= 1 {
			w.branch("eq. 30b (bb <= 1)")
		} else {
			w.branch("eq. 30a (bb > 1)")
		}
	}
	w.done(85, "eq. 28a (BUI <= 80)", "eq. 28b (BUI > 80)", "eq. 30b (bb <= 1)", "eq. 30a (bb > 1)")
}

// allSeven asserts one day's Indices against a fixture row's seven outputs.
func allSeven(ws map[string]*worst, got Indices, c fwiCase, format string, args ...any) {
	ws["FFMC"].check(got.FFMC, c.FFMC, format, args...)
	ws["DMC"].check(got.DMC, c.DMC, format, args...)
	ws["DC"].check(got.DC, c.DC, format, args...)
	ws["ISI"].check(got.ISI, c.ISI, format, args...)
	ws["BUI"].check(got.BUI, c.BUI, format, args...)
	ws["FWI"].check(got.FWI, c.FWI, format, args...)
	ws["DSR"].check(got.DSR, c.DSR, format, args...)
}

func sevenWorst(t *testing.T) (map[string]*worst, []string) {
	names := []string{"FFMC", "DMC", "DC", "ISI", "BUI", "FWI", "DSR"}
	ws := map[string]*worst{}
	for _, n := range names {
		ws[n] = newWorst(t, n)
	}
	return ws, names
}

// TestCFFDRSStep asserts Step against fwi() run for one day with batch = FALSE,
// which makes every row its own station with its own yesterday. That is exactly
// one iteration of fwi()'s loop: the RH clamp, all three codes, ISI, BUI, FWI
// and DSR — DSR has no component function upstream, so this and the two chain
// tests below are its only oracle.
//
// ledger: fwi.r
func TestCFFDRSStep(t *testing.T) {
	ws, names := sevenWorst(t)
	for _, c := range ofKind(loadFWI(t), "day") {
		y := State{FFMC: *c.FFMCYda, DMC: *c.DMCYda, DC: *c.DCYda}
		wx := Weather{TempC: c.Temp, RHPct: c.RH, WindKmh: c.WS, PrecipMm: c.Prec}
		_, got := Step(y, wx, c.Mon, latFor(c))
		allSeven(ws, got, c, "(yesterday %+v, weather %+v, month %d, lat %v, adjust %v)",
			y, wx, c.Mon, c.Lat, *c.LatAdjust)

		// The clamp is the one thing Step does that the components do not, and
		// the only rows that can see it are these.
		if c.RH >= 100 {
			ws["FFMC"].branch("RH >= 100, clamped by the driver")
		}
		if !*c.LatAdjust {
			ws["FFMC"].branch("lat.adjust = FALSE")
		}
		if c.WS >= 100 {
			ws["FFMC"].branch("very high wind")
		}
	}
	for i, n := range names {
		if i == 0 {
			ws[n].done(3000, "RH >= 100, clamped by the driver", "lat.adjust = FALSE", "very high wind")
			continue
		}
		ws[n].done(3000)
	}
}

// chains groups rows of a kind by chain, in day order, and checks each chain is
// contiguous and starts with its yesterday recorded.
func chains(t *testing.T, cases []fwiCase) map[string][]fwiCase {
	t.Helper()
	out := map[string][]fwiCase{}
	for _, c := range cases {
		out[c.Chain] = append(out[c.Chain], c)
	}
	for id, days := range out {
		sort.Slice(days, func(i, j int) bool { return days[i].Day < days[j].Day })
		for i, d := range days {
			if d.Day != i+1 {
				t.Fatalf("chain %s: day %d at position %d — the chain has a gap or a repeat", id, d.Day, i+1)
			}
		}
		if days[0].FFMCYda == nil || days[0].DMCYda == nil || days[0].DCYda == nil {
			t.Fatalf("chain %s: day 1 carries no start-up codes", id)
		}
	}
	return out
}

// runChain steps a chain from its day-1 yesterday using only this package's own
// output as each later day's yesterday — the oracle's intermediate state is
// never read. That is the difference from TestCFFDRSStep: a Step that returned
// the right day but carried the wrong thing forward passes every single-day row,
// and fails here.
func runChain(ws map[string]*worst, id string, days []fwiCase) {
	s := State{FFMC: *days[0].FFMCYda, DMC: *days[0].DMCYda, DC: *days[0].DCYda}
	for _, c := range days {
		var got Indices
		s, got = Step(s, Weather{TempC: c.Temp, RHPct: c.RH, WindKmh: c.WS, PrecipMm: c.Prec}, c.Mon, latFor(c))
		allSeven(ws, got, c, "(chain %s, day %d)", id, c.Day)
	}
}

// TestCFFDRSMultiDayChains asserts sequences of 40 to 120 days run through
// fwi() itself, at stations in every lat.adjust band of both the DMC and the
// DC, including both ends of 55-69 °N, a drought broken by a storm, and an
// autumn falling through both temperature floors.
//
// ledger: fwi.r
func TestCFFDRSMultiDayChains(t *testing.T) {
	ws, names := sevenWorst(t)
	byChain := chains(t, ofKind(loadFWI(t), "chain"))
	ids := make([]string, 0, len(byChain))
	for id := range byChain {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		days := byChain[id]
		runChain(ws, id, days)
		ws["FFMC"].branch("chain " + id)
		ws["DMC"].branch(dmcBand(days[0].Lat))
		for _, c := range days {
			if c.Prec > dcRainThreshold {
				ws["DC"].branch("rain above every threshold")
			}
			if c.Temp < -2.8 {
				ws["DC"].branch("below both temperature floors")
			}
		}
		var longest, run int
		for _, c := range days {
			if c.Prec == 0 {
				run++
				longest = max(longest, run)
			} else {
				run = 0
			}
		}
		if longest >= 20 {
			ws["DC"].branch("dry spell of 20+ days")
		}
	}
	if len(ids) < 8 {
		t.Errorf("%d chains, want at least 8", len(ids))
	}
	for _, id := range ids {
		if n := len(byChain[id]); n < 30 {
			t.Errorf("chain %s is %d days; the chains are for state propagation and should be 30+", id, n)
		}
	}
	for _, n := range names {
		switch n {
		case "DMC":
			ws[n].done(600, "lat > 30", "10 < lat <= 30", "-10 < lat <= 10",
				"-30 < lat <= -10", "-90 <= lat <= -30")
		case "DC":
			ws[n].done(600, "rain above every threshold", "below both temperature floors",
				"dry spell of 20+ days")
		default:
			ws[n].done(600)
		}
	}
}

// TestCFFDRSSampleDataset asserts cffdrs' own test_fwi sample — 48 days of real
// weather chosen by upstream rather than by this repository's generator — run
// through fwi() from its default start-up codes, which are this package's
// StartupState. It is the one fixture here none of whose inputs were picked to
// reach a branch.
//
// ledger: fwi.r
func TestCFFDRSSampleDataset(t *testing.T) {
	ws, names := sevenWorst(t)
	byChain := chains(t, ofKind(loadFWI(t), "test_fwi"))
	days, ok := byChain["test_fwi"]
	if !ok || len(byChain) != 1 {
		t.Fatalf("expected exactly one test_fwi chain, got %d", len(byChain))
	}
	start := State{FFMC: *days[0].FFMCYda, DMC: *days[0].DMCYda, DC: *days[0].DCYda}
	if start != StartupState() {
		t.Errorf("test_fwi starts from %+v, but fwi()'s default init is what StartupState "+
			"claims to be (%+v)", start, StartupState())
	}
	runChain(ws, "test_fwi", days)
	for _, n := range names {
		ws[n].done(48)
	}
}
